<a href="https://colab.research.google.com/github/Zheng7426/machine_learning_practice/blob/master/Mnist_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

Using TensorFlow backend.


11493376/11490434 [==============================] - 0s 0us/step


In [15]:
print(x_train.shape)
print(x_test.shape)

(60000, 784)
(10000, 28, 28)


In [3]:
x_train.dtype

dtype('uint8')

In [0]:
x_train = x_train.reshape((60000, 28*28))
x_train = x_train.astype('float32')

In [0]:
x_train = x_train / 255

In [0]:
x_test = x_test.reshape((10000, 28*28)).astype('float32') / 255

In [0]:
x_test[0]

<h1>Network Architecture<h1>

In [0]:
from keras import layers
from keras import models

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
network.add(layers.Dense(10, activation='softmax'))

In [21]:
print(y_train)
print(len(y_train))
print(y_train.shape)

[5 0 4 ... 5 6 8]
60000
(60000,)


In [0]:
from keras.utils import to_categorical

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [23]:
print(y_train)
print(len(y_train))
print(y_train.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
60000
(60000, 10)


In [0]:
network.compile(optimizer='rmsprop', 
                loss='categorical_crossentropy',
                metrics=['accuracy'])


In [25]:
network.fit(x_train, y_train, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 5s 78us/step - loss: 0.2609 - accuracy: 0.9247
Epoch 2/5
60000/60000 [==============================] - 4s 72us/step - loss: 0.1044 - accuracy: 0.9695
Epoch 3/5
60000/60000 [==============================] - 4s 73us/step - loss: 0.0676 - accuracy: 0.9796
Epoch 4/5
60000/60000 [==============================] - 4s 72us/step - loss: 0.0494 - accuracy: 0.9846
Epoch 5/5
60000/60000 [==============================] - 4s 73us/step - loss: 0.0371 - accuracy: 0.9884


In [26]:
test_loss, test_acc = network.evaluate(x_test, y_test)

10000/10000 [==============================] - 0s 47us/step


In [27]:
print('test_loss:', test_loss)
print('test_acc: ', test_acc)

test_loss: 0.06230161503599957
test_acc:  0.9815000295639038
